### ISSUE TITLE
Refactor server libs to make use of devDependencies

### ISSUE THREAD

**Issue by mikelax** [DMGT-TECH/the-usher-server#40]
# Feature Overview

**Is your feature request related to a problem? Please describe.**
There currently appear to be a few deps in the `server` project that are listed as dependencies but really are only using for testing / local development and thus should be moved to `devDependencies`. 

**Describe the solution you'd like**

I believe the following are safe to be moved, but this should be verified. 

* node-fetch
* nodemon

## Additional context

We may also want to consider removing the library `pg` from the server project as there should be no need for pg in the server, it is already in the database project.

**Comment by Vinitvh** [comment]
Hi @mikelax. Can I work on this?

**Comment by mikelax** [comment]
> Hi @mikelax. Can I work on this?

sure, looking forward to seeing a PR!

**Comment by Vinitvh** [comment]
@mikelax Do you want me to update `node-fetch` and `nodemon` to latest or keep the same versions? And also this changes `package-lock-json` as well. Do you want to push that changed file?

**Comment by mikelax** [comment]
@Vinitvh yes the lock file should always be checked in when the package file is updated with dependencies. As for `node-fetch`, let's stay on the same version as starting with v3 the package moved to es modules so it will be a separate refactor to make use of that.

**Comment by Vinitvh** [comment]
@mikelax Okay. Got it. Will submit a PR with these changes.
