### ISSUE TITLE
Implement Personas Admin APIs

### ISSUE THREAD

**Issue by mikelax** [DMGT-TECH/the-usher-server#59]
# Feature Overview

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

## API Design

Status | URL | Auth | Params | Notes
-- | -- | -- | -- | --
✅ | POST /personas | bearerAdminAuth | required Persona properties: body | Create a new Persona
🔍 | GET /personas/:key | bearerAdminAuth | persona key: path, required | Get a Persona
✅ | DELETE /personas/:key | bearerAdminAuth | persona key: path, required | Delete a Persona
🔍 | GET /personas | bearerAdminAuth | filter, limit ([Details](https://github.com/DMGT-TECH/the-usher-server/issues/59#issuecomment-1878848994)) | Get a list of Personas
## Implementation Notes

* The source files should be placed in the `src/api_endpoints/personas` folder

## Questions

1. For these APIs, and really all Persona APIs, should the API pattern be to use the Persona key (database field) or the `sub_claim`? The `sub_claim` is technically not fully unique, as there is also the `user_context` attribute to properly identify a unique record.
    1. What this would mean in practice is that a general use case would be to start with a `sub_claim`, then need to perform a GET Persona API to get the full Persona object to then be able to use the Persona `key` value in these APIs.
1. Do we allow optional query param flags to indicate the response should also include Roles and/or Permissions assigned to the Persona?

**Comment by k1ch** [comment]
Regarding open questions: 

1. URL pattern: I find the "persona key" more appropriate for `/personas` API. The `sub_claim` can be used in the `/tenants/:name/personas/:sub_claim` path
2. Using a query parameter to optionally include roles and permissions in the `GET:/personas/:key` endpoint is a beneficial feature. Should the permissions and roles be segregated based on clients?

@mikelax

**Comment by k1ch** [comment]
`POST /personas` Admin API is implemented in this PR https://github.com/DMGT-TECH/the-usher-server/pull/79 ✅ 

Remaining APIs: 
- `GET /personas/:key`
- `DELETE /personas/:key`

**Comment by k1ch** [comment]
@mikelax I think we should implement `GET /personas` under this issue as well. This admin API can be used to get the entire list of personas, regardless of their tenants. Also we might consider to enable simple filtering functionality through query params. 
Let me have your thoughts on that.

**Comment by mikelax** [comment]
> @mikelax I think we should implement `GET /personas` under this issue as well. This admin API can be used to get the entire list of personas, regardless of their tenants. Also we might consider to enable simple filtering functionality through query params. Let me have your thoughts on that.

Hi @k1ch , yeah if you want to go ahead and implement a `GET /personas` here are the basic requirements / test cases that I think we should have in the first deliverable. 

- The API is only accessible for users with full usher admin role/access. ie. meaning the user is in the role `the-usher:usher-admin`.
  - Having client-admin access should still return a 401 error
- There should be an optional query parameter for the tenant id to filter the results. If not provided then all personas (based on limits) should be returned. 
- The response should be an array of persona objects. I think that we should probably also include tenantkey and tenant name as additional attributes. 
- The API should support paging / limits using the established API conventions. If no limit is provided, then a default value for the number of objects returned should be used. 
- The default sort of the response should be updated_at desc (newest created / updated personas returned first)
