### ISSUE TITLE
Implement Persona Permissions Admin APIs

### ISSUE THREAD

**Issue by mikelax** [DMGT-TECH/the-usher-server#60]
# Feature Overview

Implement a set of Admin APIs to allow for the management (CRUD operations) for permissions and personas. 

## API Design

URL | Auth | Params | Notes
-- | -- | -- | --
POST /personas/:key/permissions | bearerAdminAuth | required properties -> body: `[permissionkey1, permissionkey2]` | Assign existing Permission to Persona - status `201` on success and header: `{Location: GET /personas/{key}/permissions}`
GET /personas/:key/permissions | bearerAdminAuth | persona key: path, required | List of Permissions assigned to Persona - Attributes to return: `key`, `name`, `description`, `clientkey`
DELETE /personas/:key/permissions/:permissionkey | bearerAdminAuth | persona key: path, required permissionkey: path, required| Remove Permission from Persona

## Implementation Notes

* The GET API should return an array of ~~full~~ `Permission` objects ~~, ie. the same response object as the GET Permission API.~~
    ~~* NOTE: this may require adding the `key` and `clientkey` attributes to the Permission response object~~
   * NOTE: attributes to return: `key`, `name`, `description`, `clientkey`
* The source files should be placed in the `src/api_endpoints/personas` folder

## Questions

1. For these APIs, and really all Persona APIs, should the API pattern be to use the Persona key (database field) or the `sub_claim`? The `sub_claim` is technically not fully unique, as there is also the `user_context` attribute to properly identify a unique record.
  2. What this would mean in practice is that a general use case would be to start with a `sub_claim`, then need to perform a GET Persona API to get the full Persona object to then be able to use the Persona `key` value in these APIs.
1. For the POST API to add a Permission to persona, should the body accept the Permission `key` attribute (primary key), or the `name` and the API performs the lookup to get the key? This is a pattern we need to figure out so we are consistent with implementing similar APIs. 
1. Do we implement paging for the GET method or just return the entire list in this initial implementation?

**Comment by k1ch** [comment]
@mikelax regarding `POST /personas/:key/permissions`: should we consider to handle a list of permissions to assign multiple permissions to a persona in a single call?
```js
[
  {
    permissionkey: "permission1",
    clientkey: "client1"
  },
  {
    permissionkey: "permission2",
    clientkey: "client2"
  }
]

```

**Comment by mikelax** [comment]
> @mikelax regarding `POST /personas/:key/permissions`: should we consider to handle a list of permissions to assign multiple permissions to a persona in a single call?
> 
> ```js
> [
>   {
>     permissionkey: "permission1",
>     clientkey: "client1"
>   },
>   {
>     permissionkey: "permission2",
>     clientkey: "client2"
>   }
> ]
> ```

@k1ch  generally yes, I think that we can do this as it will simplify apps making use of this API. How do you want to treat this from a restful perspective. Ie. should it return a 201 with an array of "Permission" objects. Or should it just return a 204? 

Also, we need to answer the main question on if we are going to use DB primary key columns (ie. `permissionkey`) or named "id" fields for these types of operations. I am asking the answer will dictate if we need `clientkey` to be included here.

Finally somewhat related based on the above answer, for the `GET /personas/:key/permissions` we should probably define what fields are contained for the List of objects being returned.

**Comment by k1ch** [comment]
@mikelax regarding your questions: 

1. Since the POST method is creating records on a relational table, I prefer returning status `204` and `header: {Location: GET /personas/{key}/permissions}`
2. I realized I had a typo in my initial proposal, I meant `permissionname` instead of `permissionkey`. Regardless, for the sake of simplicity we can use `permissionkey` and drop the `clientkey` info from the request body. In that case the request body can be a list of strings instead of objects. 
3. We can consider the following attributes for the permission list in the response: `key`, `name`, `description`, `clientkey`

**Comment by mikelax** [comment]
> @mikelax regarding your questions:
> 
> 1. Since the POST method is creating records on a n:n relational table, I prefer returning status `204` and `header: {Location: GET /personas/{key}/permissions}`
> 2. I realized I had a typo in my initial proposal, I meant `permissionname` instead of `permissionkey`. Regardless, for the sake of simplicity we can use `permissionkey` and drop the `clientkey` info from the request body. In that case the request body can be a list of strings instead of objects.
> 3. We can consider the following attributes for the permission list in the response: `key`, `name`, `description`, `clientkey`

@k1ch  these answers sound good to me. Do you want to update the body of this issue with these updated requirements? Thanks.

**Comment by k1ch** [comment]
`GET /personas/:key/permissions` is implemented  here: https://github.com/DMGT-TECH/the-usher-server/pull/80 ✅

Remaining: 
- `POST /personas/:key/permissions`
- `DELETE /personas/:key/permissions/:permissionkey`

**Comment by k1ch** [comment]
Completed:
- `GET /personas/:key/permissions` https://github.com/DMGT-TECH/the-usher-server/pull/80 ✅
- `POST /personas/:key/permissions` https://github.com/DMGT-TECH/the-usher-server/pull/84 ✅

Remaining:
- `DELETE /personas/:key/permissions/:permissionkey`

@mikelax can we disable the automatic closure of issues?

**Comment by mikelax** [comment]
> Completed:
> 
> * `GET /personas/:key/permissions` [Topics/k1ch/ introduce get/personas-permissions #80](https://github.com/DMGT-TECH/the-usher-server/pull/80) ✅
> * `POST /personas/:key/permissions` [Topics/k1ch/admin-post-personas-permissions #84](https://github.com/DMGT-TECH/the-usher-server/pull/84) ✅
> 
> Remaining:
> 
> * `DELETE /personas/:key/permissions/:permissionkey`
> 
> @mikelax can we disable the automatic closure of issues?

@k1ch  the [automatic linking and closing](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) of issues is part of GitHub functionality. To not close an issue don't use one of the reserved words.
