### ISSUE TITLE
GET /self/clients list using IDP Token as Authorization Header in Request

### ISSUE THREAD

**Issue by kumbharcoditas** [DMGT-TECH/the-usher-server#72]
# Feature Overview

![image](https://github.com/DMGT-TECH/the-usher-server/assets/62090911/2a6aba93-5f37-4761-a19c-f2c2c376662d)
The above API needs to be updated to take in a IDP Token as Authorization header with Bearer. This makes its more convenient for a User to use the self/clients endpoint

# Expected Behavior
Request
```shell
curl --location '/self/clients' --header 'Authorization: Bearer #IDP_Token#'
```

Response 
```json
[
  {
    "client_id": "client-app1",
    "clientname": "Client Application 1",
    "description": "An application for calling data APIs",
  },
  {
    "client_id": "client-app2",
    "clientname": "Client Application 2",
    "description": "An application for calling data APIs",
  }
]
```

## Additional context

https://treppllc.atlassian.net/browse/TRM-309 -> Requires this feature to be implemented with IDP token.

**Comment by mikelax** [comment]
@kumbharcoditas  and @k1ch before we start on this issue should we consider and answer the open question in #16 on if we should consider the `client_id` as a url slug? 

I know that PR has been open a long time, but it's very close, maybe now is the time to answer the remaining open questions, make any additional changes and get it merged.

**Comment by mikelax** [comment]
@k1ch  and @kumbharcoditas in looking over this story again I don't think that any work is needed for this. The `self` APIs are all defined with a security scheme of `bearerSelfAuth` as you can [see here](https://github.com/DMGT-TECH/the-usher-server/blob/main/server/the-usher-openapi-spec.yaml#L88). 

This means that for these APIs there is middleware that validates the Bearer JWT token in the Authorization header is valid. The `sub_claim` from the JWT is then made available for the API implementation and this is what is [used in the actual logic](https://github.com/DMGT-TECH/the-usher-server/blob/main/server/src/api_endpoints/endpoint_self_clients.js#L5). 

Again the `user_context` param here is really an optional user attribute that we are currently not making use of.

**Comment by k1ch** [comment]
Thanks @mikelax! I tested the API and it is working as expected: 
![image](https://github.com/DMGT-TECH/the-usher-server/assets/19498202/91f5c806-3508-471f-9cd9-6ec8182f43e5)

@kumbharcoditas An access token from the Persona Authorization (identity) server should be used. In your case the access_token issues by Auth0. Please confirm and close the issue.

**Comment by kumbharcoditas** [comment]
Thank you @mikelax for taking a quick look at this one, Looks like missed the lock sign on the api while using swagger editor. And Yes @k1ch we should be using the access_token from the Identity provider response. I have tested this on PROD and works as expected. Closing this issue and no work required.
